fields:
  category:
    width: 1/3
    label: Category
    type: select
    options:
      type: query
      query: site.structure.toStructure
      text: "{{ item.action }}"
      value: "{{ item.action }}"
  images:
    width: 2/3
    type: files
    label: Images du projet
    layout: cardlets
    size: tiny
    search: false
    text: "{{ file.caption }}"
  description:
    width: 1/3
    type: textarea
    size: small
